wip New steering
Flying-Octopus-Team/myszojelen pull request #17
Opened 2021-02-03 16:20 UTC by Ktwsz

2021-02-10 16:04 UTC, dyedmagenta requested changes

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/Game.gd
> +	yield(world, "world_ready")
Czemu yield?

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/Interface/Interface.gd
> +	find_node("Poll_link").connect("pressed", self, "_on_Poll_link_pressed")
W reszcie projektu używaliśmy CamelCase do nazw node'ów.
Czemu find_node?

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/Interface/Interface.gd
> +	steering_screen.find_node("SteeringContainer").reset()
Znów, nie lepiej używać get_node albo ścieżek ze znakiem '$'?

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/Interface/SteeringContainer.gd
> +		find_node(current_steering_type).downscale()
Node'y current_steering_type dynamicznie tworzysz? Może lepiej używać get_node?

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Player.gd
> +#TODO
Co tu jest do zrobienia? Do wywalenia komentarz albo dopisz proszę czego brakuje.

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Character.gd
> +#TODO
Co tu jest do zrobienia? Dopisz proszę albo usuń komentarz.

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Character.gd
> +#TODO
Znów todo, nie wiadomo o co chodzi

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/IOJK_no_rotation.gd
> +			var t = Timer.new()
Unikajmy jendoliterowych zmiennych, kod traci na czytelności. Wiadomo że to timer ale w kontekście całej tej wielkiej metody trzeba się domyślać o co chodzi z timerem.

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/IOJK_no_rotation.gd
> +func steer(delta: float) -> bool:
Myślę że warto byłoby powydzielać z metodę steer mniejsze prywatne metody. Kod zyska na czytelności

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/IOJK_rotation.gd
> +func steer(delta:float) -> bool:
Podobnie można porozdzielać ja w IOJK no rotation

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/KeyboardRotating.gd
> +#???
Komentarz do wywalenia chyba?

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Numpad.gd
> +func steer(delta: float) -> bool:
Podobnie można powydzielać metody

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Rotator.gd
> +#???
Komentarz do wywalenia

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Steering.gd
> +#	for c in get_children():
Do wywalenia zakomentowany kod. Jak będzie potrzebny to się napisze po prostu. A tak zostają takie artefakty nie wiadomo do końca do czego.

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/IOJK_no_rotation.gd
> +extends SteeringBaseScript
Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> -extends SteringBaseScript
Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_no_rotation.gd
> +extends SteeringBaseScript
Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_rotation.gd
> -extends SteringBaseScript
Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD2_no_rotation.gd
> +extends SteeringBaseScript
Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD2_rotation.gd
> +extends SteeringBaseScript
Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a

2021-02-10 16:04 UTC, dyedmagenta commented on project/src/Game/World/World.gd
> +	yield(self, "steering_chosen")
Czemu yield?

2021-02-12 12:07 UTC, dyedmagenta requested changes

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> +extends baseSteeringScript
Klasa nazywa się chyba SteeringBaseScript, nie sypie tutaj błędem?

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_no_rotation.gd
> +extends baseSteeringScript
Nazwa klasy

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_rotation.gd
> +extends baseSteeringScript
Znów nazwa

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Steering.gd
> +	get_parent().find_node("SteeringInfo").texture = SteeringDict[SteeringDictKey].texture
Find node potrzebny?

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +extends baseSteeringScript
Klasa nazywa się chyba SteeringBaseScript, nie sypie tutaj błędem?

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
Skąd ta zmienna? Ta stała z Character.Facing chyba nie wyleciała?

2021-02-12 12:07 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/baseSteeringScript.gd
> +class_name baseSteeringScript
Czemu cały plik wyleciał i zrobiłeś z nową nazwą?
Też nazwa klasy i skryptów raczej powinna być CamelCasem

2021-02-12 12:09 UTC, dyedmagenta requested changes

2021-02-12 12:09 UTC, dyedmagenta commented on project/src/Game/Interface/Interface.gd
> +#onready var steering_screen : Control = $SteeringScreen
Chyba śmieci jakieś, nie trzymajmy zakomentowanego kodu.

2021-02-12 12:18 UTC, Ktwsz commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> +extends baseSteeringScript
> Do tej pory nazywaliśmy klasy i skrypty używając CamelCase'a
Myślałem, że nazwa była do zmienienia; Teraz klasa nazywa się baseSteeringScript

2021-02-12 12:27 UTC, Ktwsz commented on project/src/Game/World/Characters/Player/Steering/baseSteeringScript.gd
> +class_name baseSteeringScript
Myślałem, że nazwa `SteeringBaseScript` jest do zmienienia

2021-02-12 12:34 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> +extends baseSteeringScript
WSAD1_double_keys.gd  jest do zmiany. SteeringBaseScript jest poprawna.
Tutaj jest opisany style guide w godot https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html

2021-02-12 12:36 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> +extends baseSteeringScript
Mea culpa, nie precyzyjnie się wyraziłem, że chodzi o nazwę tego konkretnego skryptu, a nie klasy, z której ten skrypt dziedziczy.

2021-02-12 12:40 UTC, Ktwsz commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> +extends baseSteeringScript
Mam zmienić z powrotem na `SteeringBaseScript`?

2021-02-12 12:45 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/WSAD1_double_keys.gd
> +extends baseSteeringScript
> 
> 
> Mam zmienić z powrotem na `SteeringBaseScript`?

Tak

2021-02-12 22:18 UTC, Ktwsz commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
W niektórych rodzajach sterowania w funkcji steer() była definiowana zmienna `var facing = Character.Facing`, a w niektórych było po prostu używane `Character.Facing`. Chciałem trochę ujednolicić kod i dodałem do klasy SteeringBaseScript zmienną `var facing_enum = Character.Facing`

2021-02-15 09:21 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
ahh, rozumiem to zmieniłbym po prostu nazwę na coś w rodzaju character_facing_direction i dał w SteeringBaseScript typ int dla tej zmiennej

2021-02-15 09:53 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
Myślę, że całość wygląda dobrze, także tylko ta zmienna została i można mergować

2021-02-15 11:41 UTC, Ktwsz commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
> ahh, rozumiem to zmieniłbym po prostu nazwę na coś w rodzaju character_facing_direction i dał w SteeringBaseScript typ int dla tej zmiennej

W klasie Character jest enumeracja `Facing` i zmienna `facing` (która przechowuje kierunek w którym jest zwrócona postać). Zmienna `facing_enum` ma przechowywać enumerację, a nie sam kierunek w którym jest zwrócona postać

2021-02-15 11:54 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
> 
> W klasie Character jest enumeracja `Facing` i zmienna `facing` (która przechowuje kierunek w którym jest zwrócona postać). Zmienna `facing_enum` ma przechowywać enumerację, a nie sam kierunek w którym jest zwrócona postać

Ah no to w takim razie ta zmienna bardziej miesza niż pomaga. W przypadku Character.Facing jest jasne, że jest to stała natomiast facing_enum sugeruje, że to będzie się zmieniać. Z jednej strony masz statyczny enum `Character.Facing` z drugiej zmienną.

2021-02-15 12:08 UTC, Ktwsz commented on project/src/Game/World/Characters/Player/Steering/Joystick.gd
> +		return facing_enum.TOP_RIGHT
Okej to usunę tę zmienną `facing_enum` i dam wszędzie `Character.Facing`

2021-02-15 16:44 UTC, dyedmagenta approved these changes
LGTM

2021-02-17 16:14 UTC, merged