Manu for changing steering controls
Flying-Octopus-Team/myszojelen pull request #35
Opened 2021-05-14 23:09 UTC by Ktwsz

2021-05-16 23:44 UTC, Ktwsz commented
Wizualnie jest jeszcze trochę do poprawy, ale póki co skupiam się bardziej na kodzie

2021-05-23 18:42 UTC, dyedmagenta commented
> 
> 
> Wizualnie jest jeszcze trochę do poprawy, ale póki co skupiam się bardziej na kodzie

Daj znać kiedy sprawdzić

2021-05-23 19:05 UTC, Ktwsz commented
@dyedmagenta myślę że już można w sumie

2021-05-24 22:01 UTC, dyedmagenta requested changes
Wygląda w porządku, natomiast trzeba przeorać niektóre metody, które są po prostu za duże. Takie wydzielanie na mniejsze metody zwiększa czytelność.

![](https://media.giphy.com/media/PtuayrkI1dKYo/giphy.gif)

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Player.gd
> +	if ((Input.is_action_just_pressed("shot_keyboard") and not InputMap.get_action_list("shot_keyboard").empty())
Myślę że ten warunek spokojnie powinien być w osobnej metodzie

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/4Directions.gd
> +	if (Input.is_action_pressed("4directions_up") and not InputMap.get_action_list("4directions_up").empty()):
Tu chyba warto wydzielić do osobnej metody, tym bardziej że powtarza się to w każdym ifie

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/8Directions.gd
> +	if (Input.is_action_pressed("8directions_up_left") and not InputMap.get_action_list("8directions_up_left").empty()):
Tu tak samo warto wydzielić

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/8Directions.gd
> +	return -1
Unikajmy magic numberów. https://en.wikipedia.org/wiki/Magic_number_(programming)
Warto wydzielić to minus jeden do stałej i używać tej stałej.

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/Game/World/Characters/Player/Steering/Rotating.gd
> +		player._rotate(-1)
Te -1 i 1 też wydzieliłbym do stałych

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/InputButton.gd
> +		var event = action_list[0]
Wewnątrz tego ifa można do metody osobnej wydzielić

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/InputButton.gd
> +func _pressed() -> void:
Całość w _pressed wydzieliłbym do osobnej metody, niekoniecznie wiadomo co tutaj, ma się zadziać.
Ogólnie wszędzie tam, gdzie, warto wstawić komentarz, który wyjaśnia co się dzieje powinno wydzieliać się do metody, która nazwą wyjaśnia co się dzieje

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/InputButton.gd
> +	for action_hbox in $"../../".get_children():
Te piramidkę też bym wydzielił do osobnej metody, ciężko połapać się co tu się dzieje na pierwszy rzut oka

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/InputButton.gd
> +func _input(event):
Tu też piramida do zburzenia. Naprawdę ciężko się połapać co tu się dzieje.
Cały if elif do osobnej metody, wnętrze if i elif do osobnych metod i wewnątrz na pewno tego zagnieżdżonego fora do osobnych metod trzeba wydzielić.

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/InputButton.gd
> +					if not other_action is Button or other_action == self or other_action.text != scancode:
Sam ten warunek spokojnie może być osobną metodą

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/SteeringSettings.gd
> +	match SteeringSave.steering_type:
Ten match spokojnie moze być w osobnej metodzie

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/SteeringSettings.gd
> +	match steering_string:
cały match może być w osobnej metodzie

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/MainMenu/SteeringSettings.gd
> +			get_node("Controls4Directions").show()
Tu chyba w każdym match jest to samo? `get_node` i `set_steering_type` Można też wydzielić do metody

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/PreloadedScripts/SteeringSave.gd
> +func _load_input() -> void:
Piramida do zburzenia :)

2021-05-24 22:01 UTC, dyedmagenta commented on project/src/PreloadedScripts/SteeringSave.gd
> +func save_input() -> void:
Tak samo do podziału metoda

2021-06-09 16:38 UTC, dyedmagenta approved these changes
LGTM

2021-06-09 20:09 UTC, merged